# URL for git clone
GIT_URL=https://chromium.googlesource.com/v8/v8.git

# Tag name or commit hash for checkout
GIT_VERSION=6.1.534.2

GIT_FAST=1

# Package name
NAME=libv8-6.1

# Package version
VERSION=$(GIT_VERSION)

# PPA version
PPA_VERSION=1

PPA=ppa:pinepain/libv8-experimental


include ./packaging.mk
