# URL for git clone
GIT_URL=https://chromium.googlesource.com/v8/v8.git

# Tag name or commit hash for checkout
GIT_VERSION=7.5.288.23

GIT_FAST=1

# Package name
NAME=libv8-7.5

# Package version
VERSION=$(GIT_VERSION)

# PPA version
PPA_VERSION=1

PPA=ppa:stesie/libv8


include ./packaging.mk
