#!/usr/bin/make -f

PHONY += clean

NPROCS:=$(shell grep -c ^processor /proc/cpuinfo)

clean:

x64.release:
	cd v8 ; \
	gn gen out.gn/x64.release --args="is_debug=false is_component_build=true v8_use_external_startup_data=false" ; \
	ninja -j $(NPROCS) -v -C out.gn/x64.release ; \
