# URL for git clone
GIT_URL=https://github.com/pinepain/php-v8.git

PECL_NAME=v8

# Package name
NAME=php-${PECL_NAME}

# Package version
VERSION=0.1.9

# Tag name or commit hash for checkout
GIT_VERSION="v${VERSION}"
GIT_FAST=1

# PPA version
PPA_VERSION=1

PPA=ppa:pinepain/php-v8

include ../packaging-pecl.mk
include ../packaging-base.mk
