# URL for git clone
GIT_URL=https://github.com/pinepain/php-ref.git

PECL_NAME=ref

# Package name
NAME=php-${PECL_NAME}

# Package version
VERSION=0.6.0

# Tag name or commit hash for checkout
GIT_VERSION="v${VERSION}"
GIT_FAST=1

# PPA version
PPA_VERSION=1

PPA=ppa:pinepain/experimental

include ../packaging-pecl.mk
include ../packaging-base.mk
