# URL for git clone
GIT_URL=https://chromium.googlesource.com/v8/v8.git

# Tag name or commit hash for checkout
GIT_VERSION=5.4.420

GIT_FAST=1
GIT_POST_HOOK=./load_deps.py

# Package name
NAME=libv8-5.4

# Package version
VERSION=5.4.420

# PPA version
PPA_VERSION=1

PPA=ppa:pinepain/libv8-5.4


include ../packaging.mk
